# Copyright 2025 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/tdispclaims.plugin
GOPKG := github.com/veraison/ratsd/attesters/tdispclaims
SRCS := main.go

include ../../../mk/plugin.mk
