# Copyright 2025 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/pcitsm.plugin
GOPKG := github.com/veraison/ratsd/attesters/pcitsm
SRCS := main.go

include ../../../mk/plugin.mk
