# Copyright 2025 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

SUBDIR := tsm
SUBDIR += mocktsm
SUBDIR += deviceevidence
SUBDIR += tdispclaims

clean: ; $(RM) -rf ./bin

include ../mk/subdir.mk
