# Copyright 2025 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

PLUGIN := ../../bin/deviceevidence.plugin
GOPKG := github.com/veraison/ratsd/attesters/deviceevidence
SRCS := main.go

include ../../../mk/plugin.mk
