//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for BadRequestErrorStatus.
const (
	N400 BadRequestErrorStatus = 400
)

// Defines values for BadRequestErrorTitle.
const (
	InvalidRequest BadRequestErrorTitle = "invalid request"
)

// Defines values for BadRequestErrorType.
const (
	TagGithubCom2024VeraisonratsdErrorInvalidrequest BadRequestErrorType = "tag:github.com,2024:veraison/ratsd:error:invalidrequest"
)

// Defines values for EATEatProfile.
const (
	TagGithubCom2024Veraisonratsd EATEatProfile = "tag:github.com,2024:veraison/ratsd"
)

// Defines values for OptionDataType.
const (
	Array   OptionDataType = "array"
	Boolean OptionDataType = "boolean"
	Integer OptionDataType = "integer"
	Number  OptionDataType = "number"
	Object  OptionDataType = "object"
	String  OptionDataType = "string"
)

// Defines values for UnauthorizedErrorStatus.
const (
	N401 UnauthorizedErrorStatus = 401
)

// Defines values for UnauthorizedErrorTitle.
const (
	AccessUnauthorized UnauthorizedErrorTitle = "access unauthorized"
)

// Defines values for UnauthorizedErrorType.
const (
	TagGithubCom2024VeraisonratsdErrorUnauthorized UnauthorizedErrorType = "tag:github.com,2024:veraison/ratsd:error:unauthorized"
)

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	Detail   *string               `json:"detail,omitempty"`
	Instance *string               `json:"instance,omitempty"`
	Status   BadRequestErrorStatus `json:"status"`
	Title    BadRequestErrorTitle  `json:"title"`
	Type     BadRequestErrorType   `json:"type"`
}

// BadRequestErrorStatus defines model for BadRequestError.Status.
type BadRequestErrorStatus float32

// BadRequestErrorTitle defines model for BadRequestError.Title.
type BadRequestErrorTitle string

// BadRequestErrorType defines model for BadRequestError.Type.
type BadRequestErrorType string

// ChaResRequest defines model for ChaResRequest.
type ChaResRequest struct {
	// AttesterSelection Keyed by sub-attester plugin name (e.g. "device-evidence"); each value is a flat map of string options for that sub-attester (e.g. {"pci-bdf": "0000:01:00.0"}). Generated as json.RawMessage (via x-go-type) rather than a typed Go map because the server re-unmarshals this field in two stages (first keyed by plugin name, then per-plugin options); the schema below documents the true shape without changing the handler's parsing code.
	AttesterSelection json.RawMessage `json:"attester-selection,omitempty"`
	Nonce             string          `json:"nonce"`
}

// EAT defines model for EAT.
type EAT struct {
	// Cmw Standard (padded) base64 encoding of the JSON-serialized text of a CMW Collection (see the CMWCollection schema) -- i.e. this is base64-of-JSON-text, not a base64 encoding of raw evidence bytes. Base64-decoding this field yields JSON text, which must itself be JSON-parsed to obtain the CMWCollection object; it is not ready-to-consume binary evidence on its own.
	Cmw []byte `json:"cmw"`

	// EatNonce The nonce from the request, echoed back verbatim.
	EatNonce   string        `json:"eat_nonce"`
	EatProfile EATEatProfile `json:"eat_profile"`
}

// EATEatProfile defines model for EAT.EatProfile.
type EATEatProfile string

// Option defines model for Option.
type Option struct {
	DataType OptionDataType `json:"data-type"`
	Name     string         `json:"name"`
}

// OptionDataType defines model for Option.DataType.
type OptionDataType string

// SubAttester defines model for SubAttester.
type SubAttester struct {
	Name    string    `json:"name"`
	Options *[]Option `json:"options,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError struct {
	Detail   *string                 `json:"detail,omitempty"`
	Instance *string                 `json:"instance,omitempty"`
	Status   UnauthorizedErrorStatus `json:"status"`
	Title    UnauthorizedErrorTitle  `json:"title"`
	Type     UnauthorizedErrorType   `json:"type"`
}

// UnauthorizedErrorStatus defines model for UnauthorizedError.Status.
type UnauthorizedErrorStatus float32

// UnauthorizedErrorTitle defines model for UnauthorizedError.Title.
type UnauthorizedErrorTitle string

// UnauthorizedErrorType defines model for UnauthorizedError.Type.
type UnauthorizedErrorType string

// ChaResRequestParametersAccept defines model for ChaResRequestParameters.accept.
type ChaResRequestParametersAccept = string

// RatsdCharesParams defines parameters for RatsdChares.
type RatsdCharesParams struct {
	Accept *ChaResRequestParametersAccept `json:"accept,omitempty"`
}

// RatsdCharesApplicationVndVeraisonCharesPlusJSONRequestBody defines body for RatsdChares for application/vnd.veraison.chares+json ContentType.
type RatsdCharesApplicationVndVeraisonCharesPlusJSONRequestBody = ChaResRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /ratsd/chares)
	RatsdChares(w http.ResponseWriter, r *http.Request, params RatsdCharesParams)

	// (GET /ratsd/subattesters)
	RatsdSubattesters(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RatsdChares operation middleware
func (siw *ServerInterfaceWrapper) RatsdChares(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RatsdCharesParams

	headers := r.Header

	// ------------- Optional header parameter "accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("accept")]; found {
		var Accept ChaResRequestParametersAccept
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RatsdChares(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RatsdSubattesters operation middleware
func (siw *ServerInterfaceWrapper) RatsdSubattesters(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RatsdSubattesters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/ratsd/chares", wrapper.RatsdChares)
	m.HandleFunc("GET "+options.BaseURL+"/ratsd/subattesters", wrapper.RatsdSubattesters)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RXX2/juBH/KgO2QBNUkrXbRR+06IM3DRbXYnuLJMU9rINiRI4t3kmkSo7sdQN/94Kk",
	"HMuxc0mKax4CmUPN/Obfb0YPQtqut4YMe1E9iB4ddsTk4q+rBm/I39C/B/L89VFUoJTUc7ihjahEQ6jI",
	"iUwY7EhUYhRnwsuGOgz3eNsHiWenzUrsdru9MNr5hGo0cu2cdRGIsz051hQvKGLU7RlFmdDGMxpJZ4We",
	"kYeogczQierbh7K8z/b3zNDV5MI91tzS5JrQZo2tVuASLHGfnSpPB4d3GFfVSnMz1IW0Xfa+fP+hWpND",
	"7a2ZOWSvKgruVaPy53XvMhGE2pGKioN0D/LRqcNrtv6ZJAdIRwk7DSMyk2dyuaeWJGtr4qlSOjxj+/X4",
	"9jPnzwRiAkORl073yYD4O21JQb0FP9T5HgL07bDSBkLJwAUVqwIWQtFaS8pprRUZSQtx+REIZQNrbAcC",
	"7QFh2SJDhz3YJSQIYKMlD0vrgBvkY0NJ+cNC9FLntVouRAULUZZlWZXvqrIsyoXYXRbwmQw5ZFKAHn72",
	"1hQ3uPlC3uOK4GKtEb7nK5sHZy/BITcUrRlACGcKPtuIqyaJgyfghsCTW5MDR/lgOnS+wdYDN9rDUlOr",
	"QBvgjQXPuCIPF0vtPMMv+3hNQpQFdQZ6cvl4Ojp9+TEZis0ENbV2A8rKoQsdHUXsBgLfYE+w0dzYgUE2",
	"aFYhckHeoFEtuT946NH5cCqtokI8zWsmHv0XlXgSoCi1nWbqet6KKhjdZcLYsTOX1nXIohI1evrzh8G1",
	"4qWqT+9m54r2XOlfz+9OC152m0Qf03q8ZTQKnYKLHpUidQkJFJCRVsWCWsbI/O32x3/knpzGVv+HFDB9",
	"5yBDuPryE1zZdsQDF55Svq++/DQ5Tkm5hDwHXVCREq/9aC63yzxaCGozMJYBzyFxuIF9R0C9ZfIFfEoa",
	"FI3XJiW1Df99xA5J86bRsoFu8AyaPbVLqEffQsKDXxZszajNGR9SgD+C5oA8gHSEapuzzaU1fugIam3Q",
	"bQ8YrQl2wG5MKKJD5rdM4gyNEvK/HuvkOFN3DUEUwdLZLqIbSTMDko0NbYLyF1iTq5F1d2zv+UpLRntn",
	"l7p9I4W/zNZT1VPvsliN50r3x35PxU+mHjLmT6fMaDXbT68wAZlW8am2tiU0IhPoHG5FtjdybnylYf3w",
	"UheGW9kEyjkHbod6PnbpqRfP2MnEyGBBFngjPvze0VJU4nezw1oyGxeF2Rimw8BJTp5FfA7lPw0O3FgX",
	"evn/v2e8e9WegVKS9zBMoP22u8YLmv/HTSO4THJwmre3ITspep8IHbn5wE34FdMWXqrj8aELG+Y+rYDa",
	"LG2MZwqLuJnf3cL1nkcmLPRXpM4amH/9QWRiTc4nfiiLsniXSokM9lpU4k9FWZQiEz1yE0GlaMxkgy6h",
	"7K3nU6q5arBtyawIHPneGk/BWgHzuMuGxUM+3kCjMhj6wPBDzF8Gq3F5SCP3kQq1gev5HWxmcWIkagok",
	"FWoOg+UfVHA7ILxKALOjFfzb+Y44XJm9sKLv7lOCyfMnq7ZxJlrDZGIIsO9bLSOQ2dqoYl9BRYrWH8OQ",
	"f0wlvtSfR1BSgg+1NS4E++DGTLwvy18BRMj5IBOIjzBh1b8sXlH+C/F64GF1iHBPp88YO2jQp2STIlWE",
	"kvvwq+B7Z+uWujdG8Ol30DOgxq1S2qFVcSQPRpEL9KSmMxLUQGG2779l/NYwfh/Bv/vNwZ/S6xn488R3",
	"+pjyiiNGiWU/5ZJv97v7cGFsZT/U+50wltGKzvTzZwrrVKs977e56UeBB1yjbrFu47oS16cOZaMNPdOe",
	"t1Ojb6rj0yi+atpNZ+rpyHtTsca//w4AHcNdpeoPAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
